const AUTH_SUCCESS = "AUTH_SUCCESS"
const AUTH_FAILED = "AUTH_FAILED"
const AUTH_ERROR = "AUTH_ERROR"
const NO_AUTHORIZE = "NO_AUTHORIZE"
const TOKEN_EXPIRED = "TOKEN_EXPIRED"
const AUTH_RESET = "AUTH_RESET"

export {
  AUTH_SUCCESS,
  AUTH_FAILED,
  AUTH_ERROR,
  NO_AUTHORIZE,
  TOKEN_EXPIRED,
  AUTH_RESET
}